// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Закрывает приложение.
        /// </summary>
        public void CloseAppRecordedMethod()
        {
            #region Variable Declarations
            WinButton uIЗакрытьButton = this.UIЛабораторная1Window.UIЛабораторная1TitleBar.UIЗакрытьButton;
            #endregion

            // Click 'Закрыть' button
            Mouse.Click(uIЗакрытьButton, new Point(22, 14));
        }
        
        #region Properties
        public UIЛабораторная1Window UIЛабораторная1Window
        {
            get
            {
                if ((this.mUIЛабораторная1Window == null))
                {
                    this.mUIЛабораторная1Window = new UIЛабораторная1Window();
                }
                return this.mUIЛабораторная1Window;
            }
        }
        #endregion
        
        #region Fields
        private UIЛабораторная1Window mUIЛабораторная1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIЛабораторная1Window : WinWindow
    {
        
        public UIЛабораторная1Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Лабораторная 1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Лабораторная 1");
            #endregion
        }
        
        #region Properties
        public UIЛабораторная1TitleBar UIЛабораторная1TitleBar
        {
            get
            {
                if ((this.mUIЛабораторная1TitleBar == null))
                {
                    this.mUIЛабораторная1TitleBar = new UIЛабораторная1TitleBar(this);
                }
                return this.mUIЛабораторная1TitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIЛабораторная1TitleBar mUIЛабораторная1TitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.21005.1")]
    public class UIЛабораторная1TitleBar : WinTitleBar
    {
        
        public UIЛабораторная1TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Лабораторная 1");
            #endregion
        }
        
        #region Properties
        public WinButton UIЗакрытьButton
        {
            get
            {
                if ((this.mUIЗакрытьButton == null))
                {
                    this.mUIЗакрытьButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIЗакрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Закрыть";
                    this.mUIЗакрытьButton.WindowTitles.Add("Лабораторная 1");
                    #endregion
                }
                return this.mUIЗакрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIЗакрытьButton;
        #endregion
    }
}
